
- name: Check to see if Controller was already downloaded
  stat: path={{ controller_install_dir }}
  register: st1

- name: Check to see if Euem was already downloaded
  stat: path={{ euem_install_dir }}
  register: st2


- name: Log into AppDynamics SSO
  command: /usr/bin/wget --save-cookies /tmp/cookies.txt --post-data "{{ sso_auth }}" {{ sso_url }}
  when: st1.stat.exists == false

- name: Download latest version of Controller
  command: /usr/bin/wget --content-disposition --load-cookies /tmp/cookies.txt {{ Controller_Installer_url }} -O {{ controller_installer }}
  when: st1.stat.exists == false

- name: Download latest version of EUEM
  command: /usr/bin/wget --content-disposition --load-cookies /tmp/cookies.txt {{ EUEM_Installer_url }} -O {{ euem_installer }}
  when: st2.stat.exists == false
