
- name: Install packages
  yum: pkg={{ item }} state=installed
  with_items:
      - libaio
      - libaio-devel
      - wget
      - libselinux-python

- name: Set kernel params for a happy controller
  sysctl: name=fs.file-max value=819200
  sysctl: name=net.ipv4.tcp_syn_retries value=8
  sysctl: name=vm.swappiness value=0

- name: Increase limits on open files
  lineinfile: dest=/etc/security/limits.conf line="*        soft    nofile        65535"
  lineinfile: dest=/etc/security/limits.conf line="*        hard    nofile        65535"

- name: Increase limits on process limit
  lineinfile: dest=/etc/security/limits.conf line="*        soft    nproc        8192"
  lineinfile: dest=/etc/security/limits.conf line="*        hard    nproc        8192"

- name: Create AppDynamics user
  user: name=appdynamics comment="AppDynamics" home="{{ home_dir }}" createhome=yes
